name: nnlg
description: NNLG

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.2+3

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #flutter_pickers: ^2.1.9
  dio: ^4.0.6 #网络请求
  shared_preferences: ^2.0.15 #用来存储配置文件用的
  fluttertoast: ^8.0.9 #Toast提示使用
  flutter_update_dialog: ^2.0.0 #弹窗提示插件，一般用来整更新弹窗
  #扫描二维码
  scan: ^1.6.0
  qr_code_scanner: ^1.0.1
  flutter_hms_scan_kit: ^1.0.4
  qr_flutter: ^4.0.0 #二维码生成
  path_provider: ^2.0.11 #获取文件目录使用
  image_gallery_saver: ^1.7.1 #保存图片使用
  image_picker: ^0.8.6 #本地图片选择
  amap_flutter_map: ^3.0.0 #高德地图
  amap_flutter_location: ^3.0.0 #高德定位

  flutter_svg: ^0.22.0 #用于加载svg图标

  web_socket_channel: ^2.2.0 #用于发送WebSocket

  flutter_easyrefresh: ^2.2.1 #用于下拉刷新或者加载的下拉条
  url_launcher: ^6.1.11 #用于跳转浏览器
  package_info_plus: ^4.0.2 #用于获取APP版本等相关信息
  #home_widget: ^0.3.0 #桌面小组件
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/NNLG.png
    - images/2.0x/NNLG.png
    - images/3.0x/NNLG.png
    - images/4.0x/NNLG.png
    - images/userClip.png
    - images/2.0x/userClip.png
    - images/3.0x/userClip.png
    - images/4.0x/userClip.png
    - images/open_eye.png
    - images/2.0x/open_eye.png
    - images/3.0x/open_eye.png
    - images/4.0x/open_eye.png
    - images/close_eye.png
    - images/2.0x/close_eye.png
    - images/3.0x/close_eye.png
    - images/4.0x/close_eye.png
    - images/black.webp
    - images/2.0x/black.webp
    - images/3.0x/black.webp
    - images/4.0x/black.webp
    - images/backLogin.png
    - images/2.0x/backLogin.png
    - images/3.0x/backLogin.png
    - images/4.0x/backLogin.png
    - images/user.jpg
    - images/2.0x/user.jpg
    - images/3.0x/user.jpg
    - images/4.0x/user.jpg
    - images/start.png
    - images/2.0x/start.png
    - images/3.0x/start.png
    - images/4.0x/start.png
    - images/end.png
    - images/2.0x/end.png
    - images/3.0x/end.png
    - images/4.0x/end.png
    - images/person.png
    - images/2.0x/person.png
    - images/3.0x/person.png
    - images/4.0x/person.png
    - images/course.png
    - images/2.0x/course.png
    - images/3.0x/course.png
    - images/4.0x/course.png
    - images/xiaobei_gzt.jpg
    - images/2.0x/xiaobei_gzt.jpg
    - images/3.0x/xiaobei_gzt.jpg
    - images/4.0x/xiaobei_gzt.jpg
    - images/xiaobei_title.png
    - images/2.0x/xiaobei_title.png
    - images/3.0x/xiaobei_title.png
    - images/4.0x/xiaobei_title.png
    - images/background.png
    - images/2.0x/background.png
    - images/3.0x/background.png
    - images/4.0x/background.png
    - images/bbgx.png
    - images/2.0x/bbgx.png
    - images/3.0x/bbgx.png
    - images/4.0x/bbgx.png
    - images/user_on.png
    - images/2.0x/user_on.png
    - images/3.0x/user_on.png
    - images/4.0x/user_on.png
    - images/user_off.png
    - images/2.0x/user_off.png
    - images/3.0x/user_off.png
    - images/4.0x/user_off.png
    - images/Fun_on.png
    - images/2.0x/Fun_on.png
    - images/3.0x/Fun_on.png
    - images/4.0x/Fun_on.png
    - images/Fun_off.png
    - images/2.0x/Fun_off.png
    - images/3.0x/Fun_off.png
    - images/4.0x/Fun_off.png
    - images/lyl.svg
    - images/2.0x/lyl.svg
    - images/3.0x/lyl.svg
    - images/4.0x/lyl.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
